apiVersion: v1
kind: Service
metadata:
  name: my-springboot-app-service
spec:
  selector:
    app: my-springboot-app
  ports:
    - protocol: TCP
      port: 8081    # Service exposed on port 8081
      targetPort: 8080  # Maps to container's port
  type: LoadBalancer